project:
  type: website

website:
  title: "jhelvy.com"
  favicon: favicon.ico
  site-url: https://www.jhelvy.com/
  google-analytics: "G-HQNG5WQE3X"
  cookie-consent: 
    type: express
    style: headline
    palette: dark
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/people/helveston.png"
    card-style: summary
  open-graph:
    locale: es_ES
    site-name: jhelvy.com
  search: 
    location: navbar
    type: overlay
    copy-button: true
  theme:
    light: flatly
    dark: darkly
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: css/jhelvy.css



