project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true
  render:
    - "index.qmd"
    - "about.qmd"
    - "projects.qmd"
    - "research.qmd"
    - "teaching.qmd"
    - "404.qmd"
  resources:
    - "content/"
    - "css"
    - "static/"

website:
  title: "Mei Dong"
  description: "The personal website of Mei Dong"
  image: "images/meidong.png"
  site-url: https://MeiDongstat.github.io/
  repo-url: https://github.com/MeiDongstat/MeiDongstat.github.io
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false
  google-analytics: "G-HQNG5WQE3X"
  open-graph:
    locale: es_ES
    site-name: https://MeiDongstat.github.io
  twitter-card:
    creator: "@meidong"
    site: "@meidong"
    image: images/meidong.png
    card-style: summary  
    image-height: 150
    image-width: 150
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
  page-footer:
    center:
      - text: "<a href='https://drive.google.com/file/d/16cbtvPXwVsk1reVhhkkwvKViH0d4dUNc/view?usp=sharing'>CV</a> &nbsp;<a href='https://github.com/MeiDongstat' target='blank'><i class='bi bi-github'></i></a> &nbsp;<a href='https://www.linkedin.com/in/mei-dong-297392128/' target='blank'><i class='bi bi-linkedin'></i></a> &nbsp;<a href='https://scholar.google.com/citations?user=L--4tCAAAAAJ&hl=en  ' target='blank'><i class='ai ai-google-scholar fa-lg'></i></a> &nbsp;<a href='https://www.researchgate.net/profile/Mei-Dong-8?ev=hdr_xprf' target='blank'><i class='ai ai-researchgate fa-lg'></i></a> &nbsp;<a href='https://orcid.org/my-orcid?orcid=0000-0003-1735-5361' target='blank'><i class='ai ai-orcid fa-lg'></i></a><br>Site made with quarto</a><br>© 2025 Mei Dong"

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: 
      - "_includes/header.html"
      - "_includes/no-favicon.html" 
