project:
  type: website

website:
  title: "jhelvy.com"
  subtitle: Personal website of John Paul Helveston
  listing:
    feed: true
    contents: posts
  favicon: favicon.ico
  site-url: https://www.jhelvy.com/
  google-analytics: "G-HQNG5WQE3X"
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/people/helveston.png"
    card-style: summary
  open-graph:
    locale: es_ES
    site-name: jhelvy.com
  search: 
    location: navbar
    type: overlay
    copy-button: true
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Lab
        href: lab.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Talks
        href: talks.qmd
      - text: Projects
        href: project.qmd
      - text: Blog
        href: blog.qmd
      - icon: fas fa-bars
        menu:
        - text: "CV"
          href: content/docs/Helveston_CV.pdf
        - icon: github
          href: https://github.com/jhelvy
        - icon: twitter
          href: https://twitter.com/JohnHelveston
        - icon: linkedin
          href: https://www.linkedin.com/in/jhelvy
        - icon: rss
          href: blog.xml

format:
  html:
    theme: "css/jhelvy.scss"
    css: "css/jhelvy.css"
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"
